# The name of this app. Must be unique within a project.
name: app

# The runtime the application uses. The 'type' key defines the base container
# image that will be used to run the application. There is a separate base
# container image for each primary language for the application,
# in multiple versions. Check the Python documentation
# (https://docs.platform.sh/languages/python.html#supported-versions)
# to find the supported versions for the 'python' type.
type: 'python:3.10'

# The size of the persistent disk of the application (in MB).
disk: 512

# The relationships of the application with services or other applications.
#
# The left-hand side is the name of the relationship as it will be exposed
# to the application in the PLATFORM_RELATIONSHIPS variable. The right-hand
# side is in the form '<service name>:<endpoint name>'.
relationships:
    database: db:postgresql

hooks:
    build: |
      set -e

      pip install --user poetry
      poetry install
      poetry run ./manage.py collectstatic

    deploy: |
      poetry run ./manage.py migrate

web:
  commands: 
    start: poetry run gunicorn -b 0.0.0.0:$PORT --access-logfile - keyvee.wsgi

  locations:
    /:
      allow: false
      passthru: true

    /static:
      root: static
      allow: true
      passthru: false
      expires: 12h

variables:
  env:
    ENV: production-platformsh
