# Generated by Django 4.1.1 on 2022-09-27 06:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blob",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2022, 9, 27, 6, 26, 7, 346435, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="blob",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
